### ISSUE TITLE
Error on conversation creation/save

### ISSUE THREAD

**Issue by matthewmoss** [benedikt/layer-ruby#17]
When rapidly creating new conversations, I have been encountering the following error on conversation creation or when saving an updated convo:

```
RestClient::InternalServerError (500 Internal Server Error):
  app/controllers/api/v1/users_controller.rb:78:in `block in create'
  app/controllers/api/v1/users_controller.rb:58:in `create'
```

Update:
```
conversation = Layer::Conversation.find(classroom.conversation_id)
conversation.participants << user.id.to_s
conversation.save
```

Create:
```
conversation = Layer::Conversation.create({participants: [user.id.to_s]})
conversation.metadata = data
conversation.messages.create({ sender: { name: 'Server' }, parts: [{ body: conversation_starter, mime_type: 'text/plain' }]})
conversation.save
```

**Comment by benedikt** [comment]
Hi!

This error is a server error on Layer itself. There's nothing this gem can do to prevent that from happening. 

Try rescuing the exception and retrying the request.

Hope this helps!

Benedikt
