### ISSUE TITLE
NoMethodError: private method `include' called for #<Class:#<Layer::RelationProxy:0x007fd1f67016e0>>

### ISSUE THREAD

**Issue by geoffreymm** [benedikt/layer-ruby#7]
Hey!

The gem works perfectly on development but on staging (using Heroku) I'm experiencing an error. When I try to create a message for a Layer::Conversation instance it throws:

```
NoMethodError: private method `include' called for #<Class:#<Layer::RelationProxy:0x007fd1f67016e0>>
	from /app/vendor/bundle/ruby/2.0.0/gems/attr_encrypted-1.3.4/lib/attr_encrypted.rb:259:in `method_missing'
	from /app/vendor/bundle/ruby/2.0.0/gems/layer-ruby-0.4.1/lib/layer/relation_proxy.rb:10:in `block in initialize'
	from /app/vendor/bundle/ruby/2.0.0/gems/layer-ruby-0.4.1/lib/layer/relation_proxy.rb:10:in `each'
	from /app/vendor/bundle/ruby/2.0.0/gems/layer-ruby-0.4.1/lib/layer/relation_proxy.rb:10:in `initialize'
	from /app/vendor/bundle/ruby/2.0.0/gems/layer-ruby-0.4.1/lib/layer/conversation.rb:8:in `new'
	from /app/vendor/bundle/ruby/2.0.0/gems/layer-ruby-0.4.1/lib/layer/conversation.rb:8:in `messages'
	from (irb):10
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.1.4/lib/rails/commands/console.rb:90:in `start'
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.1.4/lib/rails/commands/console.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.1.4/lib/rails/commands.rb:17:in `<top (required)>'
	from /app/bin/rails:4:in `require'
	from /app/bin/rails:4:in `<main>'
```

I'm using the same keys from layer for the Development and Staging environments. 

Thank you!

**Comment by geoffreymm** [comment]
It was related with the Ruby version. It didn't work with v. 2.0.0, just updated to 2.2.0 and everything worked fine. :-)

**Comment by benedikt** [comment]
Thanks for reporting this. I'll look into this anyways, but I feel like it should work with 2.0.0 as well! :)
